### ISSUE TITLE
Searching videos for a channel returns a bunch of errors but works afterwards.

### ISSUE THREAD

**Issue by Nassim-Saboundji** [valerebron/usetube#4]
```
get date error for KW4JlxAEAE0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for RwlnCn2EB9o, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for 7ITtPPE-pXE, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for ObhvacfIOg0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for SnpAAX9CkIc, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for E7sm-0nGV34, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for A1x6Jy2CYNo, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for vmIgjAM0uh0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for KHbQ6ti5BQ0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for KHbQ6ti5BQ0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for KHbQ6ti5BQ0, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for fqKGl6exyyY, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for i5C1Uj7jJCg, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for AezAN2RcO8Y, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for gg0Nbfzo_00, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
get date error for 6RHH7M4siPM, try again TypeError: Cannot read property 'player_response' of undefined
    at /Users/macpro/node_modules/usetube/dist/usetube.js:41:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macpro/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
However after all those errors it ends up working. So I wonder why it does this?

**Comment by valerebron** [comment]
Hi Nassim !
Usetube retrieve youtube data with simple http request,
unfortunetly youtube don't give precise videodate information on search result.
In order to get precise date usetube make another request for each video, these request somtimes failed, that's why you get this error.
But usetube try again in that case.
So I decide to hide these warnings in the future version (1.1.4).

Cheers,
Valère
