### ISSUE TITLE
TypeError: Cannot read property 'sectionListRenderer' of undefined

### ISSUE THREAD

**Issue by Pixel1011** [valerebron/usetube#7]
search videos error, terms: outsmarted TypeError: Cannot read property 'sectionListRenderer' of undefined
    at Object.<anonymous> (/home/pixel/Discord/js/pixelator/node_modules/usetube/dist/usetube.js:76:53)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pixel/Discord/js/pixelator/node_modules/usetube/dist/usetube.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

not sure what is causing it but it keeps popping up when i search for a video and i just have to loop it until the error stops occuring and a search result comes through

**Comment by valerebron** [comment]
It should be ok with next version.
